group_imports = "StdExternalCrate"
imports_granularity = "Module"
max_width = 120
comment_width = 100
wrap_comments = true
overflow_delimited_expr = true
normalize_comments = true
unstable_features = true
